version: '3'

services:
  db:
    image: postgres
    environment: 
      DB_USER: postgres
      DB_PASSWORD: 14psa9714
      DB_HOST: localhost
      DB_NAME: chronometer
      DB_PORT: 5432
      FRONT_URL: http://localhost:3000
      PORT: 3001
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    image: chronometer-backend
    depends_on: 
      - db
    ports:
      - "3001:3001"
    env_file:
        "./api/.env"
    build:
      context: ./api
      dockerfile: ./Dockerfile
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "frontend"
    ports:
      - "3000:3000"
    links:
      - "backend:be"