version: '3.7'

services:  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword      
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - "5432"

  backend:
    image: cristianhr/backend
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on: 
      - db
    ports:
      - "3001:3001"
    expose: 
      - "3001"
    env_file:
        "./api/.env" 
    volumes:
      - ./api:/opt/app

  frontend:
    image: cristianhr/frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    expose:
      - "3000"
    env_file:
      "./client/.env"
    volumes:
      - ./client:/opt/app
