version: '3.9'

services:  

  db:
    image: "postgres"
    environment: 
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: docker
    volumes: 
      - data:/var/lib/postgresql/data
    mem_limit: 256m
    mem_reservation: 64M
    cpus: 0.5

  db-test:
    image: "postgres"
    environment: 
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: docker
    volumes: 
      - data-test:/var/lib/postgresql/data
    ports:
      - 5430:5432
    mem_limit: 256m
    mem_reservation: 64M
    cpus: 0.5

  api:
    build: ./api
    ports:
      - "3001:3001"
    depends_on: 
      - db
      - db-test
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: docker 
    mem_limit: 256m
    mem_reservation: 64M
    cpus: 0.5

  client:
    build: ./client
    ports:
      - "80:3000"
    environment:
      BACKEND_DOCKER_URL: "api:3001"
    mem_limit: 1024m
    mem_reservation: 128M

volumes: 
  data:
